# Generated by Django 3.2.9 on 2021-12-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('projects', '0002_rename_created_by_project_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_client', to='client.client'),
        ),
    ]
